Feature/home page form
Drewbi/startify pull request #13
Opened 2020-06-03 11:30 UTC by FocalChord

Closes #12

2020-06-03 12:04 UTC, Drewbi requested changes
Good stuff, just a couple of ez changes for now :)

2020-06-03 12:04 UTC, Drewbi commented on pages/index.tsx
> +    // Make API Call with JSON.stringify(values);
We will just be rerouting to /home/:seed so you will need to generate a random number to be used as the seed and add the options in some way, either `/home/94829483?type=e_commerce` or  `/home/e_commerce-94829483` or you could encode the type to make it less obvious what we're doing eg. `/home/MVPWG33NNVSXEY3F-94829483`

2020-06-03 12:04 UTC, Drewbi commented on pages/index.tsx
> +        <p> Made by Team 2 in Pod 0.3.2 </p>
```suggestion
        <p> Made by Team 1 in Pod 0.3.2 </p>
```
I think we are Team 1

2020-06-03 12:04 UTC, Drewbi commented on pages/index.tsx
> +          background-color: #e2dadb;
Maybe stick with white for the background

2020-06-04 04:39 UTC, laveesh approved these changes
:+1:

2020-06-04 04:44 UTC, Drewbi approved these changes

2020-06-04 04:45 UTC, Drewbi approved these changes

2020-06-04 04:45 UTC, merged