Extra .gitignore entries
Drewbi/startify pull request #8
Opened 2020-06-03 07:37 UTC by Drewbi

Fixes #4

2020-06-03 20:56 UTC, laveesh requested changes

2020-06-03 20:56 UTC, laveesh commented on .gitignore
> +*.lnk
```suggestion
*.lnk

```

2020-06-04 04:35 UTC, FocalChord approved these changes
Good work!

2020-06-04 04:37 UTC, laveesh approved these changes
:+1:

2020-06-04 04:39 UTC, merged